---

- name: Install Java on system
  package:
    name: "{{ item }}"
    state: present
  loop:
    - "openjdk-11-jdk"
    - "java-1.8.0-openjdk"
  when: ansible_os_family == "Debian" or ansible_os_family == "RedHat"

- name: Download ElasticSearch
  get_url:
    url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.15.3-linux-x86_64.tar.gz"
    dest: "/tmp/elasticsearch-8.15.3.tar.gz"
    mode: '0644'

- name: Create Elastisearch installatoin dir
  file:
    path: "/opt/elasticsearch"
    state: directory
    mode: '0755'

- name: extract elastisearch
  ansible.builtin.unarchive:
    src: "/tmp/elasticsearch-8.15.3.tar.gz"
    dest: "/opt/elasticsearch"
    remote_src: yes
    creates: "/opt/elasticsearch/elasticsesarch-8.15.3"

- name: create link for elastisearch
  file:
    src: "/opt/elasticsearch/elasticsearch-8.15.3"
    dest: "/opt/elastisearch/elasticsearch"
    state: link

- name: check for elastiserch data in dir
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "/var/lib/elasticsearch"
    - "var/log/elasticsearch"

- name: set up elasticsearch.yml config
  template:
    src: "elasticsearch.yml.j2"
    dest: "/opt/elasticsearch/elasticsearch/config/elasticsearch.yml"
    mode: '0644'

- name: set elasticsearch permission
  file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: '0755'
  loop:
    - "/opt/elasticsearch"
    - "/var/lib/elasticserach"
    - "/var/log/elasticsearch"

- name: set up elasticserch systemctl service
  copy:
    dest: /etc/systemd/system/elasticsearch.service
    content: |
      [Unit]
      Description=ElasticSearch
      Documentaiton=https://www.elastic.co
      Wants=network-online.target
      After=network-online.target

      [Service]
      Type=simple
      User=root
      Group=root
      ExecStart=/opt/elasticsearch/elasticsearch/bin/elasticsearch -p /var/run/elasticsearch/elasticsearch.pid
      StandardOutput=journal
      StandardError=inherit
      LimitNOFILE=65535
      Restart=always
      TimeoutStopSec=0
      KillSignal=SIGTERM
      SendSIGKILL=no
      SuccessExitStatus=143

      [Install]
      WantedBy=multi-user.target

- name: Reload systemd to apply elastiserch service
  systemd:
    daemon_reload: true

- name: start and enable elasticsearch
  systemd:
    name: elasticsearch
    state: started
    enabled: True


